---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sds-project

---
# PDF Converter Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-converter
  namespace: sds-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-converter
  template:
    metadata:
      labels:
        app: pdf-converter
        project: sds-demo    # <--- NEW: Shared label for spreading
    spec:
      nodeSelector:
        node-type: worker
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              project: sds-demo # <--- NEW: Looks for ANY project pod
      containers:
        - name: pdf-converter
          image: kanisornp/sds-project-pdf-renderer:1.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"   # Lowered request to allow scheduling
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          # --- FIXED PROBES (Use TCP Socket instead of HTTP) ---
          livenessProbe:
            failureThreshold: 5
            tcpSocket:          # Check if port is open, not URL
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

---
# PDF Converter Service
apiVersion: v1
kind: Service
metadata:
  name: pdf-converter
  namespace: sds-project
spec:
  selector:
    app: pdf-converter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# IPYNB Converter Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipynb-converter
  namespace: sds-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipynb-converter
  template:
    metadata:
      labels:
        app: ipynb-converter
        project: sds-demo    # <--- NEW
    spec:
      nodeSelector:
        node-type: worker
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              project: sds-demo # <--- NEW
      containers:
        - name: ipynb-converter
          image: kanisornp/sds-project-html-converter:1.1
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          # --- FIXED PROBES ---
          livenessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 5001
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 10

---
# IPYNB Converter Service
apiVersion: v1
kind: Service
metadata:
  name: ipynb-converter
  namespace: sds-project
spec:
  selector:
    app: ipynb-converter
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

---
# Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: sds-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        project: sds-demo    # <--- NEW
    spec:
      nodeSelector:
        node-type: worker
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              project: sds-demo # <--- NEW
      containers:
        - name: gateway
          image: kanisornp/sds-project-gateway:1.2
          ports:
            - containerPort: 3000
          env:
            - name: IPYNB_SERVICE
              value: "http://ipynb-converter:5001"
            - name: PDF_SERVICE
              value: "http://pdf-converter:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # --- FIXED PROBES ---
          livenessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10

---
# Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: sds-project
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sds-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        project: sds-demo    # <--- NEW
    spec:
      nodeSelector:
        node-type: worker
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              project: sds-demo # <--- NEW
      containers:
        - name: frontend
          image: kanisornp/sds-project-frontend:1.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Frontend usually serves HTML at /, so httpGet is okay here, 
          # but tcpSocket is safer if you aren't sure.
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sds-project
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# Ingress for Frontend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: sds-project
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
